spring:
  application:
    name: back
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  issuer: https://bookheaven.com
  secret-key: c10da1aa67519f393bb808ac03dde4092ce7188ba5ff52413c4a876acc4bce73
  duration: 1
  refresh-duration: 60
  refresh-key: c10da1aa67519f393bb808ac03dde4092ce7188ba5ff52413c4a876acc4bce74

server:
  port: 1271
