spring:
  application:
    name: back
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  issuer: https://bookheaven.com
  secret-key: c10da1aa67519f393bb808ac03dde4092ce7188ba5ff52413c4a876acc4bce73c10da1aa67519f393bb808ac03dde4092
  duration: 1
  refresh-duration: 60
  refresh-key: c10da1aa67519f393bb808ac03dde4092ce7188ba5ff52413c4a876acc4bce74c10da1aa67519f393bb808ac03dde4092

server:
  port: 1271

mybatis:
  mapper-locations: classpath*:mapper/*.xml

  type-aliases-package: com.bookheaven.back.domain # XML에서 엔티티 타입을 간단히 쓸 수 있게 한다
  configuration:
    map-underscore-to-camel-case: true

